# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c8bf945525759df26b035e6a399ba45563d58403579f74ec7847238dc478e345e89d566ca6d57afbb11c89e92c37fbb81d67cf6d54e1fb9eacd32ce3e3838da7

test:
  secret_key_base: d39344b95ac0043d2a89d69c1cdb3c1d0441d7b6e391056907b72be4e0eff0ed0c26390a6777eb2f952f33b739367a9f619402713803725a278a5443f2915ef6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
